USE [master]
GO
/****** Object:  Database [Ristorante]    Script Date: 01/05/2024 10:51:33 ******/
CREATE DATABASE [Ristorante]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ristorante', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ristorante.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ristorante_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ristorante_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Ristorante] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ristorante].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ristorante] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ristorante] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ristorante] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ristorante] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ristorante] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ristorante] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ristorante] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ristorante] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ristorante] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ristorante] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ristorante] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ristorante] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ristorante] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ristorante] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ristorante] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ristorante] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ristorante] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ristorante] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ristorante] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ristorante] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ristorante] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ristorante] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ristorante] SET RECOVERY FULL 
GO
ALTER DATABASE [Ristorante] SET  MULTI_USER 
GO
ALTER DATABASE [Ristorante] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ristorante] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ristorante] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ristorante] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ristorante] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ristorante] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ristorante', N'ON'
GO
ALTER DATABASE [Ristorante] SET QUERY_STORE = ON
GO
ALTER DATABASE [Ristorante] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [Ristorante]
GO
/****** Object:  User [RistoranteWebApp]    Script Date: 01/05/2024 10:51:33 ******/
CREATE USER [RistoranteWebApp] FOR LOGIN [RistoranteWebApp] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [RistoranteWebApp]
GO
/****** Object:  Table [dbo].[Indirizzi]    Script Date: 01/05/2024 10:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Indirizzi](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Via] [varchar](100) NOT NULL,
	[NumeroCivico] [varchar](10) NOT NULL,
	[Citta] [varchar](50) NOT NULL,
	[CAP] [char](5) NOT NULL,
 CONSTRAINT [PK_Indirizzi] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordini]    Script Date: 01/05/2024 10:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordini](
	[Numero] [int] IDENTITY(1,1) NOT NULL,
	[Data] [datetime] NOT NULL,
	[IdIndirizzo] [int] NOT NULL,
	[IdUtente] [int] NOT NULL,
 CONSTRAINT [PK_Ordini2] PRIMARY KEY CLUSTERED 
(
	[Numero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Portate]    Script Date: 01/05/2024 10:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Portate](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[Prezzo] [decimal](8, 2) NOT NULL,
	[Tipo] [int] NOT NULL,
 CONSTRAINT [PK_Portate] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Utenti]    Script Date: 01/05/2024 10:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Utenti](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Nome] [varchar](100) NULL,
	[Cognome] [varchar](100) NULL,
	[Password] [varchar](100) NOT NULL,
	[Ruolo] [int] NOT NULL,
 CONSTRAINT [PK_Utenti] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VociOrdine]    Script Date: 01/05/2024 10:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VociOrdine](
	[NumeroOrdine] [int] NOT NULL,
	[IdPortata] [int] NOT NULL,
	[Quantita] [int] NOT NULL,
 CONSTRAINT [PK_VociOrdine] PRIMARY KEY CLUSTERED 
(
	[NumeroOrdine] ASC,
	[IdPortata] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ordini]  WITH CHECK ADD  CONSTRAINT [FK_Ordini_Indirizzi] FOREIGN KEY([IdIndirizzo])
REFERENCES [dbo].[Indirizzi] ([Id])
GO
ALTER TABLE [dbo].[Ordini] CHECK CONSTRAINT [FK_Ordini_Indirizzi]
GO
ALTER TABLE [dbo].[Ordini]  WITH CHECK ADD  CONSTRAINT [FK_Ordini_Utenti] FOREIGN KEY([IdUtente])
REFERENCES [dbo].[Utenti] ([Id])
GO
ALTER TABLE [dbo].[Ordini] CHECK CONSTRAINT [FK_Ordini_Utenti]
GO
ALTER TABLE [dbo].[VociOrdine]  WITH CHECK ADD  CONSTRAINT [FK_VociOrdine_Ordini] FOREIGN KEY([NumeroOrdine])
REFERENCES [dbo].[Ordini] ([Numero])
GO
ALTER TABLE [dbo].[VociOrdine] CHECK CONSTRAINT [FK_VociOrdine_Ordini]
GO
ALTER TABLE [dbo].[VociOrdine]  WITH NOCHECK ADD  CONSTRAINT [FK_VociOrdine_Portate] FOREIGN KEY([IdPortata])
REFERENCES [dbo].[Portate] ([Id])
GO
ALTER TABLE [dbo].[VociOrdine] NOCHECK CONSTRAINT [FK_VociOrdine_Portate]
GO
USE [master]
GO
ALTER DATABASE [Ristorante] SET  READ_WRITE 
GO
